### ISSUE TITLE
Enable Disqus & Gratipay

### ISSUE THREAD

**Issue by pavi2410** [domhnallohanlon/thunkable_extensions#10]
Disqus will useful to clarify any doubts if anyone has any.

Gratipay will help to fund this project, which may help you all in keeping the site updated or buy a dedicated TLD.

**Comment by conorshipp** [comment]
I think that Disqus is a good idea. But, would we have a dedicated page for comments or comments under each article?

I don't think we need a TLD, this project was supposed to be getting put under the official Thunkable.com domain, but I'm not sure if this is going to happen or when.

**Comment by pavi2410** [comment]
Comments should be better under each article.

**Comment by SivagiriVisakan** [comment]
I don't think we need Disqus as all the posts have the links to their respective topics in the community..So if anyone has any doubts ,they can ask it directly in the community
